In [93]:
import numpy as np

In [95]:
# Array Creation:
# Create a 1-dimensional array of integers from 1 to 10.

In [97]:
array_1d = np.arange(1, 11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
# Create a 2-dimensional array with random float values of shape (3, 4).

In [101]:
array_2d = np.random.random((3, 4))
array_2d

array([[0.44341572, 0.82367879, 0.08167624, 0.09690339],
       [0.25669548, 0.04080471, 0.50496103, 0.72874513],
       [0.3983859 , 0.48019673, 0.21250343, 0.10139556]])

In [103]:
# Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [183]:
array_3d = np.zeros((2, 3, 4))
array_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [109]:
# Array Operations:

# Given two 1-dimensional arrays, perform element-wise addition,
# subtraction, multiplication, and division.

In [111]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])


In [113]:
addition = arr1 + arr2
addition

array([6, 6, 6, 6, 6])

In [115]:
subtraction = arr1 - arr2
subtraction

array([-4, -2,  0,  2,  4])

In [117]:
multiplication = arr1 * arr2
multiplication

array([5, 8, 9, 8, 5])

In [119]:
division = arr1 / arr2
division

array([0.2, 0.5, 1. , 2. , 5. ])

In [121]:
# Calculate the mean, median, and standard deviation of a given 1-
# dimensional array.

In [123]:
mean = np.mean(arr1)
mean

3.0

In [125]:
median = np.median(arr1)
median

3.0

In [127]:
std_dev = np.std(arr1)
std_dev

1.4142135623730951

In [129]:
# Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
# 4).

In [181]:
array_reshape = array_1d.reshape((3, 4))
array_reshape

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
# Array Indexing and Slicing:

# Extract the first row and last column of a 2-dimensional array.

In [139]:
first_row = array_2d[0, :]
first_row

array([0.44341572, 0.82367879, 0.08167624, 0.09690339])

In [143]:
last_column = array_2d[:, -1]
last_column

array([0.09690339, 0.72874513, 0.10139556])

In [ ]:
# Reverse the order of elements in a 1-dimensional array.

In [145]:
reversed_array = array_1d[::-1]
reversed_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# Select elements from a 2-dimensional array that satisfy a specific
# condition (e.g., values greater than a certain threshold).

In [147]:
conditioned_elements = array_2d[array_2d > 0.4]
conditioned_elements

array([0.44341572, 0.82367879, 0.50496103, 0.72874513, 0.48019673])

In [ ]:
# Array Broadcasting:

# Add a scalar value to each element of a 2-dimensional array.\

In [155]:
scalar = array_2d + 3
scalar

array([[3.44341572, 3.82367879, 3.08167624, 3.09690339],
       [3.25669548, 3.04080471, 3.50496103, 3.72874513],
       [3.3983859 , 3.48019673, 3.21250343, 3.10139556]])

In [ ]:
# Multiply a 1-dimensional array with a 2-dimensional array, leveraging
# NumPy's broadcasting rules.

In [161]:
multiplied_array = array_1d[:4] * array_2d
multiplied_array

array([[0.44341572, 1.64735758, 0.24502872, 0.38761357],
       [0.25669548, 0.08160943, 1.51488309, 2.91498053],
       [0.3983859 , 0.96039346, 0.63751029, 0.40558226]])

In [ ]:
# Linear Algebra:

# Calculate the dot product of two 1-dimensional arrays.

In [163]:
dot_product = np.dot(arr1, arr2)
dot_product

35

In [ ]:
# Compute the matrix multiplication of two 2-dimensional arrays.

In [169]:
matrix_a = np.random.randint(1, 5, (2, 3))
matrix_b = np.random.randint(1, 5, (3, 2))
matrix_multiplication = np.dot(matrix_a, matrix_b)
matrix_multiplication

array([[22, 19],
       [22, 19]])

In [ ]:
# Find the inverse and determinant of a square matrix.

In [177]:
square_matrix = np.array([[4, 7], [2, 6]])
matrix_inverse = np.linalg.inv(square_matrix)
matrix_inverse

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [179]:
matrix_determinant = np.linalg.det(square_matrix)
matrix_determinant

10.000000000000002